POST http://127.0.0.1:8000/clients/ HTTP/1.1
content-type: application/json

{
    "name": "Drogon Targaryen", 
    "email": "drogon@dracarys.com",
    "cpf": "44567891810"
}


###########################################
###Consultar pelo email

GET http://127.0.0.1:8000/clients/khaleesi@dracarys.com HTTP/1.1
content-type: application/json

