POST http://127.0.0.1:8000/address/ HTTP/1.1
content-type: application/json

{
    "zipcode": "01210200",
    "street": "Schwabl Zombie Dog",
    "city": "Red Cave",
    "state": "Land of Ooo"
}


###########################################
###Consultar todos os endereços

GET http://127.0.0.1:8000/address/ HTTP/1.1
content-type: application/json


###########################################
###Consultar pelo zipcode

GET http://127.0.0.1:8000/address/2123131515 HTTP/1.1
content-type: application/json


