POST http://127.0.0.1:8000/address/ HTTP/1.1
content-type: application/json

{
    "zipcode": "05406180",
    "street": "Cotton Candy Mount",
    "city": "Cotton Candy Land",
    "state": "Land of Ooo"
}


###########################################
###Consultar todos os endereços

GET http://127.0.0.1:8000/address/ HTTP/1.1
content-type: application/json


###########################################
###Consultar pelo zipcode

GET http://127.0.0.1:8000/address/2123131515 HTTP/1.1
content-type: application/json


