POST http://127.0.0.1:8000/clients/ HTTP/1.1
content-type: application/json

{
    "name": "Jake The Dog 2", 
    "email": "jake2@adventuretime.com",
    "cpf": "12345678910"
}


###########################################
###Consultar pelo email

GET http://127.0.0.1:8000/clients/finn@adventuretime.com HTTP/1.1
content-type: application/json


###########################################
###Listar todos os clientes

GET http://127.0.0.1:8000/clients/ HTTP/1.1
content-type: application/json
