POST http://127.0.0.1:8000/deliveryaddress/jake@adventuretime.com/05406180 HTTP/1.1
content-type: application/json

{
    "street_number": 1236,
    "complement": "2nd cave",
    "is_delivery": "false"
}


###########################################
###Consultar todos os endereços

GET http://127.0.0.1:8000/deliveryaddress/finn@adventuretime.com HTTP/1.1
content-type: application/json


