##########################################
###Registrar produto
POST http://127.0.0.1:8000/products/ HTTP/1.1
content-type: application/json

{
    "name": "Smartphone Motorola",
    "description": "O smartphone Moto E7 é perfeito para te ajudar nas tarefas básicas do dia a dia, como utilizar aplicativos de mensagens, ligações e envio de SMS. Possui um design elegante, sofisticado e moderno. Sua câmera frontal tem a resolução de 5MP, já as traseiras possuem 48MP e 2MP de resolução. A tela de 6,5 polegadas IPS Max Vision conta com resolução HD+ para garantir uma ótima visualização ao assistir seus conteúdos favoritos, como filmes e séries. Com 32GB de armazenamento interno, ele é ideal para guardar suas fotos, músicas ou vídeos! E se mesmo assim achar pouco, você pode usar um cartão MicroSD de até 512GB para aumentar essa capacidade. Possui o processador MediaTek Helio G2 Octa-Core juntamente com sua memória RAM de 2GB. Fique sempre conectado com a tecnologia 4G em um aparelho dual chip e tenha bateria para navegar o dia todo com 4000mAh. O leitor de impressão digital garante que os seus conteúdos e dados fiquem sempre super protegidos.",
    "price": 809.10,
    "quantity": 10,
    "image": "http://127.0.0.1:8000/produto/Smartphone.png",
    "code": 123456789,
    "attributes": {
        "RAM_memory": "2G",
        "technology": "4G",
        "connectivity": "Bluetooth - Wi-Fi",
        "processor": "Octa-Core",
        "operational_system": "Android"
    }
}

###########################################
###Consultar pelo codigo

GET http://127.0.0.1:8000/products/code/12345678102 HTTP/1.1
content-type: application/json

###########################################
###Consultar produto pelo nome

GET http://127.0.0.1:8000/products/name/Smartphone HTTP/1.1
content-type: application/json

##########################################
###Atualizar produto pelo código

PATCH http://127.0.0.1:8000/products/123456789  HTTP/1.1
content-type: application/json

{
    "name": "Smartphone Motorola Moto E7 32GB Cinza Metálico"
}

###########################################
###Remover produto pelo código

DELETE http://127.0.0.1:8000/products/123456789 HTTP/1.1
content-type: application/json
