POST http://127.0.0.1:8000/shopcarts/finn@adventuretime.com/123456789 HTTP/1.1
content-type: application/json


{ 
    "quantity_product": 2   
}

###########################################
###Atualizar carrinho aberto

PATCH http://127.0.0.1:8000/shopcarts/finn@adventuretime.com/12345678102 HTTP/1.1
content-type: application/json


{ 
    "quantity_product": 1   
}


###########################################
###Consultar carrinho aberto

GET http://127.0.0.1:8000/shopcarts/opened/finn@adventuretime.com/ HTTP/1.1
content-type: application/json


###########################################
###Consultar carrinho fechado

GET http://127.0.0.1:8000/shopcarts/closed/finn@adventuretime.com/ HTTP/1.1
content-type: application/json


###########################################
###Fechar carrinho

PUT http://127.0.0.1:8000/shopcarts/close/finn@adventuretime.com/ HTTP/1.1
content-type: application/json